# just a copy of the main docker-compose
version: "3.8"
services:
  # Docker connection string: postgres://postgres:postgres@localhost:5432/
  heooow:
    container_name: "heooow"
    hostname: "heooow"
    restart: always
    environment:
      DATABASE_URL: "postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public" # change maskanplus-database:5432 to server ip:5432 for prisma cloud
      NEXT_PUBLIC_DOMAIN: "http://localhost:3000"
    build:
      context: .
    volumes:
      - heooow-volume:./prisma/dev.db
    ports:
      # systemPort:containerPort
      - "3000:3000"

volumes:
  heooow-volume:
