# just a copy of the main docker-compose
version: "3.8"
services:
  # Docker connection string: postgres://postgres:postgres@localhost:5432/
  heooow:
    container_name: "heooow"
    hostname: "heooow"
    restart: always
    build:
      context: .
    volumes:
      - heooow-volume:/app/prisma
    ports:
      # systemPort:containerPort
      - "3000:3000"

volumes:
  heooow-volume:
